project:
  type: website

website:
  title: "AO_Final_Project"
  navbar:
    background: secondary
    foreground: primary
    left:
      - href: index.qmd
        text: Home
      - Map.qmd
      - text: "Download the Report"
        file: Report.qmd
        

format:

  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    linkcolor: "blue"
    backgroundcolor: hsl(84% 50% 100%)
    fontcolor: black
    mainfont: monospace
    

editor: visual

